### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by Zeijls** [martendebruijn/web-app-from-scratch-1920#10]
https://github.com/martendebruijn/web-app-from-scratch-1920/blob/c67265cdeca1d45b4c11454935ecf3c6e48bae18/docs/js/app.js#L27-L43

Ik zie dat je in dit stukje code 2x een functie in een functie hebt geschreven, misschien dat je hier nog even naar kunt kijken dat het wat netter is! 

Als je simpelere functies schrijft die iets returen, die je andere functies aanroepen. Zodat het minder complex is.

**Comment by martendebruijn** [comment]
Ik zal proberen om hier nog even naar te kijken!

**Comment by martendebruijn** [comment]
```js
  changeSliderValue: function(sliderEl, outputEl) {
    sliderEl.oninput = function input() {
      console.log(this);
      const colorValue = this.value;
      const result = document.querySelector('.resultColor');
      const redValue = color.getSliderValue().r;
      const greenValue = color.getSliderValue().g;
      const blueValue = color.getSliderValue().b;

      outputEl.innerText = colorValue;
      result.style.backgroundColor = `rgb(${redValue}, ${greenValue}, ${blueValue})`;
    };
  },
```

Ik heb de de code herschreven naar de bovenstaande code Ik heb nu nog steeds een functie in een functie. Dit heb ik zo gedaan zodat ik de on-input functie kan hergebruiken met verschillende elementen door deze mee te geven in de argumenten van de functie die om de input functie heen zit.

```js
  changeAllSliderValues: function() {
    const redSlider = document.querySelector('#red');
    const redOutput = document.querySelector('#redOutput');
    const greenSlider = document.querySelector('#green');
    const greenOutput = document.querySelector('#greenOutput');
    const blueSlider = document.querySelector('#blue');
    const blueOutput = document.querySelector('#blueOutput');

    this.changeSliderValue(redSlider, redOutput);
    this.changeSliderValue(greenSlider, greenOutput);
    this.changeSliderValue(blueSlider, blueOutput);
  },
```
In bovenstaande functie word de individuele sliders aangeroepen.

De functie gebruikt ook de getSliderValue die de huidige waardes van de sliders terug geeft.
```js
  getSliderValue: function() {
    const red = document.querySelector('#red');
    const green = document.querySelector('#green');
    const blue = document.querySelector('#blue');
    const redValue = red.value;
    const greenValue = green.value;
    const blueValue = blue.value;
    return { r: redValue, g: greenValue, b: blueValue };
  }
```
