### ISSUE TITLE
Review aan de hand van Rubric

### ISSUE THREAD

**Issue by MarjoleinAardewijn** [martendebruijn/web-app-from-scratch-1920#11]
Criteria:
De code bevat geen syntaxfouten en is netjes opgemaakt
> Goed, ziet er goed uit tot nu toe en is goed begrijpelijk.

Code is correct gescoped en opgedeeld in modules die overeen komen met het actor diagram.
> Voldoende, De modules die je tot nu toe hebt komen goed overeen met je actor diagram.

JSON data kan met een asynchrone request worden opgehaald uit een API
> Voldoende, je werkt met een promise (fetch()).

JSON data kan, minimaal met de methodes; map, filter en reduce worden gemanipuleerd
> Nog niet aanwezig.

JSON data kan, al dan niet met een micro library, client side in de HTML worden gerenderd. Nadelen van het client-side renderen van HTML kunnen worden benoemd.
> Nog niet aanwezig.

Routing & states kunnen, al dan niet met een micro library, worden gemanaged.
> Nog niet aanwezig.

De user flow en object / class flow zijn visueel gemaakt.
> Voldoende, interaction diagram is goed te begrijpen.

De interface bevat feedback naar de gebruiker op het moment dat er gewacht moet worden op het laden van data.
> Nog niet aanwezig.

**Comment by martendebruijn** [comment]
Op basis van deze feedback heb ik een aantal features toegevoegd!
