### ISSUE TITLE
Set language

### ISSUE THREAD

**Issue by qiubee** [martendebruijn/web-app-from-scratch-1920#4]
I see in your HTML that you write text in Dutch, but your language is set on English: https://github.com/martendebruijn/web-app-from-scratch-1920/blob/4fbf171eafdb4a0ae2c3ef8d892fd07abbebc03a/docs/index.html#L2

Just change it to NL and your fine:
```html
<html lang="nl"> 
```

**Comment by martendebruijn** [comment]
Ik heb het aangepast!
