### ISSUE TITLE
app.js

### ISSUE THREAD

**Issue by Zeijls** [martendebruijn/web-app-from-scratch-1920#5]
Volgens mij kun je deze code ook in een module onderverdelen en hoeft niet in de app.js te staan. 

const rgbToHex = function(rgb) {
  let hex = Number(rgb).toString(16);
  if (hex.length < 2) {
    hex = '0' + hex;
  }
  return hex;
};

const changeFullColor = (function() {
  const redSlider = document.querySelector('#red');
  const redOutput = document.querySelector('#redOutput');
  const greenSlider = document.querySelector('#green');
  const greenOutput = document.querySelector('#greenOutput');
  const blueSlider = document.querySelector('#blue');
  const blueOutput = document.querySelector('#blueOutput');
  let resultHex = '';

  let colorObject = {
    red: redSlider.value,
    green: greenSlider.value,
    blue: blueSlider.value,
  };
  function changeValue(sliderEl, outputEl) {
    sliderEl.oninput = function() {
      const key = this.id;
      outputEl.innerText = this.value;
      colorObject[key] = rgbToHex(this.value);
      resultHex = colorObject.red + colorObject.green + colorObject.blue;
      Object.keys(colorObject).forEach(key => {
        colorObject[key] = ('0' + colorObject[key]).slice(-2);
      });
      const resultEl = document.querySelector('.result-color');
      resultEl.style.backgroundColor = '#' + resultHex;
    };
  }
  changeValue(redSlider, redOutput);
  changeValue(greenSlider, greenOutput);
  changeValue(blueSlider, blueOutput);
})();

**Comment by martendebruijn** [comment]
Ik heb de code opgesplitst in modules.
