### ISSUE TITLE
Interactive Diagram (DATA) 

### ISSUE THREAD

**Issue by Zeijls** [martendebruijn/web-app-from-scratch-1920#8]
De data in je interactive diagram zou nog voor je render functie moeten staan.

https://minor-web-1920.slack.com/files/UT536NWUQ/FTUDW0MGF/actordiagram.jpg
https://minor-web-1920.slack.com/files/UT536NWUQ/FTF45FX19/interactiondiagram.jpg

**Comment by martendebruijn** [comment]
Interaction diagram bijgewerkt
