### ISSUE TITLE
Interactive Diagram (Pijlen)

### ISSUE THREAD

**Issue by Zeijls** [martendebruijn/web-app-from-scratch-1920#9]
In de les hadden ze aangegeven dat je de pijlen in je interactive diagram achterwegen kunt laten. Omdat het hierdoor lijkt dat de data maar 1 richting op gaat terwijl dat niet in alle gevallen zo is

**Comment by martendebruijn** [comment]
Ik heb in het interaction diagram pijlen gezet bij de functies die iets meeneemt naar de andere functie.
